better logging

diff --git a/track b/track
--- a/track
+++ b/track
@@ -4,11 +4,11 @@ file="$1"
 dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
 pidfile=${HOME}/play_next.pid
 
+trap cleanup SIGINT SIGTERM ERR EXIT
+
 function log {
     echo $(date "+%Y-%m-%d %T") :: $*
 }
-
-trap cleanup SIGINT SIGTERM ERR EXIT
 
 function cleanup {
     trap - SIGINT SIGTERM ERR EXIT
@@ -22,6 +22,11 @@ function cleanup {
 if [ ! -f ${pidfile} ]; then
     log "nothing to track"
     exit 1
+fi
+
+if [ ! -f "$file" ]; then
+    log "missing file we're tracking"
+    exit 2
 fi
 
 pid=$(cat ${pidfile})
